### ISSUE TITLE
A minor mistake in readme file

### ISSUE THREAD

**Issue by happygirlzt** [malteos/semantic-document-relations#1]
Firstly, many thanks for your wonderful work. I found a minor problem in the readme file. In order to unzip the data, `-d` has been missed, it should be `bzip2 -d enwiki-20191101-pages-articles.weighted.10k.jsonl.bz2`, otherwise, it will raise an error `bzip2: Input file enwiki-20191101-pages-articles.weighted.10k.jsonl.bz2 already has .bz2 suffix.`

**Comment by happygirlzt** [comment]
Also, I wonder why 'z' is missing in these two commands; if I am not wrong, 'z' is for unzipping the files: `tar -xzf train_testdata__4folds.tar.gz` and `tar -xzf model_wiki.bert_base__joint__seq512.tar.gz`. Why not `tar -zxzf train_testdata__4folds.tar.gz` and `tar -zxzf model_wiki.bert_base__joint__seq512.tar.gz`

**Comment by malteos** [comment]
Thanks for your feedback. I fixed that bzip command. 

The tar command should be correct. It's -x for extract, -z for gzip, -f for file.
